#!/bin/bash
#
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
#
#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
xcompmgr -n &


#
# SCREEN CONFIGURATION
#

# We handle our screen configuration using xrandr. You are likely to want to
# edit this section to match the specific demands of your setup. The below
# setup is for a Lenovo W520 laptop that sometimes has an external monitor
# hooked up via either VGA or DVI, positioned to the left of the laptop.
#
# Note that you can run xrandr at the command line to get a list of your
# connected screens and find out what names you should use to refer to them.

# Activate primary screen
xrandr --output LVDS1 --auto

# If we find that a screen is connected via VGA, activate it and position it
# to the left of the primary screen.
#xrandr | grep 'VGA-1 connected' | ifne xrandr --output VGA-1 --auto --primary --left-of LVDS

# If we find that a screen is connected via HDMI, activate it and position it
# to the right of the primary screen.
xrandr | grep 'HDMI1 connected' | ifne xrandr --output HDMI1 --auto --primary --right-of LVDS1

# we're doing this in startup-hook script, because it doesn't seem to work as expected here

#
# LOAD SCREEN BACKGROUNDS
#

# To set your backgrounds, run nitrogren /path/to/images
nitrogen --restore &

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
#setxkbmap -option 'ctrl:nocaps'

# Custom initializations
xrdb -merge ~/.Xdefaults
dropbox start &
gnome-settings-daemon &
unity-settings-deamon &
gnome-panel &
eval "$(ssh-agent)" &
ssh-add &
#export SSH_ASKPASS=/usr/bin/ssh-askpass
#ssh-add < /dev/null
redshift -l 43:1.44 &
google-chrome &
nautilus &
subl &

# Now, finally, start xmonad
exec xmonad

1
