#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.

# Remmina remote desktop connection client (-i: start hidden)
if [ -z "$(pgrep remmina)" ] ; then
    remmina -i &
fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested)
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

# I disabled my touchpad because I hate those things. You can find the id
# of a device you want to disable using "xinput list"; unfortunately it can
# change depending on what devices you have plugged into USB. We extract the
# id of the device from the output of xinput, then use it to disable the
# device
TOUCHPAD_ID=`xinput | grep 'Synaptics TouchPad' | cut -f 2 | cut -f 2 -d =`
xinput set-prop $TOUCHPAD_ID "Device Enabled" 0

# Current configuration is LDVS1 - HDMI1
xrandr --output HDMI1 --auto --primary --right-of LVDS1